{{- range .Values.apps }}
{{- if .service }}
{{- $app := . }}
{{- $slots := list "" }}
{{- if and .blueGreen .blueGreen.enabled }}
  {{- $slots = list "blue" "green" }}
{{- end }}

{{- range $slot := $slots }}
{{- $name := $app.name }}
{{- if $slot }}
  {{- $name = printf "%s-%s" $app.name $slot }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $app.namespace | default $.Values.global.namespace }}
  labels:
    {{- include "appshpere.labels" $ | nindent 4 }}
    app: {{ $app.app }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - name: http-port
      protocol: TCP
      port: {{ $app.ports.port }}
      targetPort: {{ $app.ports.targetPort | default $app.ports.port }}
      {{- if $app.ports.nodePort }}
      nodePort: {{ $app.ports.nodePort }}
      {{- end }}
    {{- if $app.ports.grpcPort }}
    - name: grpc-port
      protocol: TCP
      port: {{ $app.ports.grpcPort }}
      targetPort: {{ $app.ports.grpcTargetPort | default $app.ports.grpcPort }}
      {{- if $app.ports.grpcNodePort }}
      nodePort: {{ $app.ports.grpcNodePort }}
      {{- end }}
    {{- end }}
  type: {{ $app.service.type | default "ClusterIP" }}
{{- end }}
{{- end }}
{{- end }}