{{- range .Values.apps }}
{{- if .service }}
{{- $app := . }}
{{- $slots := list "active" }}
{{- if and .blueGreen .blueGreen.enabled }}
  {{- $slots = list "active" "blue" "green" }}
{{- end }}

{{- range $slot := $slots }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ if eq $slot "active" }}{{ $app.name }}{{ else }}{{ $app.name }}-{{ $slot }}{{ end }}
  namespace: {{ $app.namespace | default $.Values.global.namespace }}
  labels:
    {{- include "appshpere.labels" $ | nindent 4 }}
    app: {{ $app.app }}
spec:
  selector:
    app: {{ $app.name }}
    {{- if eq $slot "active" }}
      {{- if and $app.blueGreen $app.blueGreen.enabled }}
    slot: {{ if ge (int $app.blueGreen.blue.weight) (int $app.blueGreen.green.weight) }}blue{{ else }}green{{ end }}
      {{- end }}
    {{- else }}
    slot: {{ $slot }}
    {{- end }}
  ports:
    - name: http-port
      protocol: TCP
      port: {{ $app.ports.port }}
      targetPort: {{ $app.ports.targetPort | default $app.ports.port }}
      {{- if $app.ports.nodePort }}
      nodePort: {{ $app.ports.nodePort }}
      {{- end }}
    {{- if $app.ports.grpcPort }}
    - name: grpc-port
      protocol: TCP
      port: {{ $app.ports.grpcPort }}
      targetPort: {{ $app.ports.grpcTargetPort | default $app.ports.grpcPort }}
      {{- if $app.ports.grpcNodePort }}
      nodePort: {{ $app.ports.grpcNodePort }}
      {{- end }}
    {{- end }}
  type: {{ $app.service.type | default "ClusterIP" }}
{{- end }}
{{- end }}
{{- end }}