{{- range .Values.apps }}
{{- if and .hpa .hpa.enabled }}
{{- $app := . }}
{{- $slots := list "default" }}
{{- if and .blueGreen .blueGreen.enabled }}
  {{- $slots = list "blue" "green" }}
{{- end }}

{{- range $slot := $slots }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ if eq $slot "default" }}{{ $app.name }}{{ else }}{{ $app.name }}-{{ $slot }}{{ end }}-hpa
  namespace: {{ $app.namespace | default $.Values.global.namespace }}
  labels:
    {{- include "appshpere.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ if eq $slot "default" }}{{ $app.name }}{{ else }}{{ $app.name }}-{{ $slot }}{{ end }}
  minReplicas: {{ $app.hpa.minReplicas }}
  maxReplicas: {{ $app.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $app.hpa.targetCPUUtilizationPercentage }}
    {{- if $app.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $app.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}