{{- range $appName, $appValues := .Values.apps }}
{{- if and $appValues.hpa $appValues.hpa.enabled }}
{{- $app := $appValues }}
{{- $slots := list "" }}
{{- if and $app.blueGreen $app.blueGreen.enabled }}
  {{- $slots = list "blue" "green" }}
{{- end }}

{{- range $slot := $slots }}
{{- $name := $app.name }}
{{- if $slot }}
  {{- $name = printf "%s-%s" $app.name $slot }}
{{- end }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}-hpa
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "appshpere.labels" $ | nindent 4 }}
    app: {{ $app.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ $app.hpa.minReplicas }}
  maxReplicas: {{ $app.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $app.hpa.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
{{- end }}