{{- range .Values.apps }}
{{- if and .hpa .hpa.enabled }}
{{- $app := . }}
{{- range $color := list "blue" "green" }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $app.name }}-{{ $color }}-hpa
  namespace: {{ $app.namespace | default $.Values.global.namespace }}
  labels:
    {{- include "appshpere.labels" $ | nindent 4 }}
    app: {{ $app.app }}
    color: {{ $color }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $app.name }}-{{ $color }}
  minReplicas: {{ $app.hpa.minReplicas }}
  maxReplicas: {{ $app.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $app.hpa.targetCPUUtilizationPercentage }}
    {{- if $app.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $app.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}