{{- if  and .Values.gateway .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.gateway.name }}-route
  namespace: {{ .Values.gateway.namespace }}
spec:
  parentRefs:
{{- range .Values.gateway.listeners }}
    {{- if .tls }}
    # Bind to HTTPS listener
    - name: {{ $.Values.gateway.name }}
      sectionName: {{ .host | replace "." "-" }}-https
    {{- if not .sslRedirect }}
    # Bind to HTTP listener (Redirect disabled)
    - name: {{ $.Values.gateway.name }}
      sectionName: {{ .host | replace "." "-" }}-http
    {{- end }}
    {{- else }}
    # Bind to HTTP listener
    - name: {{ $.Values.gateway.name }}
      sectionName: {{ .host | replace "." "-" }}-http
    {{- end }}
{{- end }}
  hostnames:
{{- range .Values.gateway.listeners }}
    - {{ .host | quote }}
{{- end }}

  rules:
{{- range .Values.gateway.listeners }}
{{- $host := .host }}

{{- range .routes }}
    - matches:
        - headers:
            - name: Host
              value: {{ $host | quote }}
          path:
            type: {{ .pathType }}
            value: {{ .path | quote }}
      backendRefs:
        - name: {{ .backend.service }}
          port: {{ .backend.port }}
      {{- if .filters }}
      filters:
        {{- toYaml .filters | nindent 8 }}
      {{- end }}
{{- end }}

{{- end }}
{{- end }}
