---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: console-appshpere-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "appshpere.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    {{- range .Values.ingress.rules }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.service }}
                port:
                  number: {{ .backend.port }}
          {{- end }}
    {{- end }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}