{{- if and .Values.gateway.enabled .Values.gateway.config }}
apiVersion: gateway.nginx.org/v1alpha1
kind: NginxProxy
metadata:
  name: {{ .Values.gateway.name }}-config
  namespace: {{ .Values.gateway.namespace }}
spec:
{{- if .Values.gateway.config.nginxDirectives }}
  nginxDirectives:
    {{- toYaml .Values.gateway.config.nginxDirectives | nindent 4 }}
{{- end }}
{{- if .Values.gateway.config.patches }}
  patches:
    {{- toYaml .Values.gateway.config.patches | nindent 4 }}
{{- end }}
{{- end }}
