{{- range .Values.apps }}
{{- if and .pdb .pdb.enabled }}
{{- $app := . }}
{{- $slots := list "" }}
{{- if and .blueGreen .blueGreen.enabled }}
  {{- $slots = list "blue" "green" }}
{{- end }}

{{- range $slot := $slots }}
{{- $name := $app.name }}
{{- if $slot }}
  {{- $name = printf "%s-%s" $app.name $slot }}
{{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}-pdb
  namespace: {{ $app.namespace | default $.Values.global.namespace }}
  labels:
    {{- include "appshpere.labels" $ | nindent 4 }}
spec:
  minAvailable: {{ $app.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      app: {{ $name }}
{{- end }}
{{- end }}
{{- end }}
