{{- range .Values.apps }}
{{- if and .pdb .pdb.enabled }}
{{- $app := . }}
{{- $slots := list "default" }}
{{- if and .blueGreen .blueGreen.enabled }}
  {{- $slots = list "blue" "green" }}
{{- end }}

{{- range $slot := $slots }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ if eq $slot "default" }}{{ $app.name }}{{ else }}{{ $app.name }}-{{ $slot }}{{ end }}-pdb
  namespace: {{ $app.namespace | default $.Values.global.namespace }}
  labels:
    {{- include "appshpere.labels" $ | nindent 4 }}
spec:
  {{- if $app.pdb.minAvailable }}
  minAvailable: {{ $app.pdb.minAvailable }}
  {{- end }}
  {{- if $app.pdb.maxUnavailable }}
  maxUnavailable: {{ $app.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $app.name }}
      {{- if ne $slot "default" }}
      slot: {{ $slot }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}

